# Grafana のデータソース(データの取り出し先)を自動で登録します。
apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 5s

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
